/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raisemeup.view;

import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import raisemeup.control.RaiseMeUp;
import raisemeup.model.beans.Job;
import raisemeup.model.beans.Pet;

/**
 *
 * @author lekogabor
 */
public class AdminPetsJobs extends javax.swing.JFrame {

    
    Pet pet = new Pet();
    Map<Integer, Job> jobs = new HashMap<Integer, Job>();
    
    /**
     * Creates new form AdminPetsJobs
     */
    public AdminPetsJobs(Pet pet) {
        this.pet = pet;
        initComponents();
        myInit();
    }
    
    private void myInit(){
        listJobs();
        
        jobs = RaiseMeUp.listJobs();
        
        for (Map.Entry<Integer, Job> job : jobs.entrySet()){
            comboJobs.addItem(job.getValue().getTitle());
        }
    }
    
    private void listJobs(){
        DefaultTableModel modelJob = (DefaultTableModel) tableJobs.getModel();
        modelJob.setRowCount(0);

        for (Map.Entry<Job, Integer> job : pet.getOwnedjobs().entrySet()){
            //System.out.println(i.getValue().getUsername());
            modelJob.addRow(new Object[]{job.getKey().getId(), job.getKey().getTitle(), job.getKey().getSpecies(),
            job.getKey().getLength(), job.getValue()});
            //System.out.println(((Food)item.getKey()).getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableJobs = new javax.swing.JTable();
        butBack = new javax.swing.JButton();
        comboJobs = new javax.swing.JComboBox();
        butSetFood = new javax.swing.JButton();
        spinTimeworked = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel1.setText("Pet's Jobs");

        tableJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "jobID", "title", "species", "length", "timeworked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableJobs);

        butBack.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butBack.setText("Back");
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        comboJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJobsActionPerformed(evt);
            }
        });

        butSetFood.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butSetFood.setText("Set");
        butSetFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSetFoodActionPerformed(evt);
            }
        });

        spinTimeworked.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel2.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel2.setText("Timeworked (sec)");

        jLabel3.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel3.setText("All Jobs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butSetFood)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(spinTimeworked, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboJobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butSetFood, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinTimeworked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
        RaiseMeUp.setAdminPets(new AdminPets());
        this.setVisible(false);
        RaiseMeUp.getAdminPets().setVisible(true);
    }//GEN-LAST:event_butBackActionPerformed

    private void comboJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJobsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJobsActionPerformed

    private void butSetFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSetFoodActionPerformed
        boolean foundFood = false;

        for (Map.Entry<Job, Integer> job : pet.getOwnedjobs().entrySet()){
            if (job.getKey().getTitle().equals(comboJobs.getSelectedItem().toString())){
                //System.out.println("spinvalue: " + spinPieceFood.getValue().toString());
                
                foundFood = true;
                if (Integer.parseInt(spinTimeworked.getValue().toString()) == job.getKey().getLength()){
                    RaiseMeUp.removeJobOwned(pet, job.getKey());
                    pet.getOwnedjobs().remove(job.getKey());
                } else {
                    job.setValue(Integer.parseInt(spinTimeworked.getValue().toString()));
                    RaiseMeUp.updateJobOwned(pet, job.getKey(), job.getValue());
                }
                break;
            }
        }
        if (!foundFood){
            for (Map.Entry<Integer, Job> job : jobs.entrySet()){
                if (job.getValue().getTitle().equals(comboJobs.getSelectedItem().toString()) && 
                        Integer.parseInt(spinTimeworked.getValue().toString()) < job.getValue().getLength()){
                    pet.getOwnedjobs().put(job.getValue(), Integer.parseInt(spinTimeworked.getValue().toString()));
                    RaiseMeUp.newJobOwned(pet, job.getValue(), Integer.parseInt(spinTimeworked.getValue().toString()));
                    break;
                }
            }
        }
        listJobs();

        System.out.println(comboJobs.getSelectedItem().toString());
    }//GEN-LAST:event_butSetFoodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPetsJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPetsJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPetsJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPetsJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPetsJobs(new Pet()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBack;
    private javax.swing.JButton butSetFood;
    private javax.swing.JComboBox comboJobs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinTimeworked;
    private javax.swing.JTable tableJobs;
    // End of variables declaration//GEN-END:variables
}
