/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raisemeup.view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import raisemeup.control.RaiseMeUp;
import raisemeup.model.beans.Food;

/**
 *
 * @author lekogabor
 */
public class AdminFoods extends javax.swing.JFrame {
    
    private Map<Integer, Food> foods = new HashMap<Integer, Food>();
    /**
     * Creates new form AdminFoods
     */
    public AdminFoods() {
        initComponents();
        myInit();
    }
    
    private void myInit(){
        
        listFoods();
        
        tableFoods.addMouseListener(new MouseAdapter(){
            
            public void mouseClicked(MouseEvent e){
                DefaultTableModel model = (DefaultTableModel) tableFoods.getModel();
                int i = tableFoods.getSelectedRow();

                
                texFoodName.setText(model.getValueAt(i, 1).toString());
                texFoodPrice.setText(model.getValueAt(i, 2).toString());
                texValuedog.setText(model.getValueAt(i, 3).toString());
                texValuecat.setText(model.getValueAt(i, 4).toString());
                texValuefish.setText(model.getValueAt(i, 5).toString());
                texValuepenguin.setText(model.getValueAt(i, 6).toString());
                texFoodImage.setText(model.getValueAt(i, 7).toString());
            }
        });
    }

    
    private void listFoods(){
        foods = RaiseMeUp.listFoods();        
        DefaultTableModel model = (DefaultTableModel) tableFoods.getModel();
        model.setRowCount(0);
        
        for (Map.Entry<Integer, Food> f : foods.entrySet()){
            //System.out.println(f.getValue().getName());
            model.addRow(new Object[]{f.getValue().getId(), f.getValue().getName(), f.getValue().getPrice(), f.getValue().getValuedog(),
                                    f.getValue().getValuecat(), f.getValue().getValuefish(), f.getValue().getValuepenguin(),
                                    f.getValue().getImage()});
        }
    }
    
    
    private void clearTextFields(){
        texFoodName.setText("");
        texFoodPrice.setText("");
        texFoodImage.setText("");
        texValuedog.setText("");
        texValuecat.setText("");
        texValuefish.setText("");
        texValuepenguin.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFoods = new javax.swing.JTable();
        texFoodImage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        texValuepenguin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        texValuecat = new javax.swing.JTextField();
        texValuefish = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        texValuedog = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        texFoodPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        texFoodName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        butUpdate = new javax.swing.JButton();
        butRemove = new javax.swing.JButton();
        butAdd = new javax.swing.JButton();
        butBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel1.setText("Food");

        tableFoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "foodID", "name", "price", "valuedog", "valuecat", "valuefish", "valuepenguin", "image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableFoods);

        texFoodImage.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel10.setText("Image");

        texValuepenguin.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel9.setText("Valuepenguin");

        texValuecat.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N

        texValuefish.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel8.setText("Valuefish");

        jLabel7.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel7.setText("Valuecat");

        texValuedog.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel6.setText("Valuedog");

        texFoodPrice.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel5.setText("Price");

        texFoodName.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel4.setText("Name");

        butUpdate.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butUpdate.setText("Update");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        butRemove.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butRemove.setText("Remove");
        butRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRemoveActionPerformed(evt);
            }
        });

        butAdd.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butAdd.setText("Add");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });

        butBack.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butBack.setText("Back");
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(41, 41, 41))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(46, 46, 46))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(22, 22, 22))))
                                    .addGap(26, 26, 26)
                                    .addComponent(texFoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(texFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(texFoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(texValuedog, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(texValuecat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(texValuepenguin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(texValuefish, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(butAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(butRemove)
                        .addGap(64, 64, 64)
                        .addComponent(butUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(texFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(texFoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(texValuedog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(texValuecat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(texValuefish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(texValuepenguin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(texFoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAdd)
                    .addComponent(butRemove)
                    .addComponent(butUpdate)
                    .addComponent(butBack))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
        RaiseMeUp.setAdminWindow(new AdminWindow());
        this.setVisible(false);
        RaiseMeUp.getAdminWindow().setVisible(true);
    }//GEN-LAST:event_butBackActionPerformed

    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        Food f = new Food();
        f.setName(texFoodName.getText());
        f.setPrice(Integer.parseInt(texFoodPrice.getText()));
        f.setValuedog(Integer.parseInt(texValuedog.getText()));
        f.setValuecat(Integer.parseInt(texValuecat.getText()));
        f.setValuefish(Integer.parseInt(texValuefish.getText()));
        f.setValuepenguin(Integer.parseInt(texValuepenguin.getText()));
        f.setImage(texFoodImage.getText());
        
        RaiseMeUp.newFood(f);
        clearTextFields();
        listFoods();
    }//GEN-LAST:event_butAddActionPerformed

    private void butRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRemoveActionPerformed
        Food f = new Food();
        f.setName(texFoodName.getText());
        RaiseMeUp.removeFood(f);
        clearTextFields();
        listFoods();
    }//GEN-LAST:event_butRemoveActionPerformed

    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableFoods.getModel();
        int i = tableFoods.getSelectedRow();

        Food f = new Food();
        
        f.setId(Integer.parseInt(model.getValueAt(i, 0).toString()));
        f.setName(texFoodName.getText());
        f.setPrice(Integer.parseInt(texFoodPrice.getText()));
        f.setValuedog(Integer.parseInt(texValuedog.getText()));
        f.setValuecat(Integer.parseInt(texValuecat.getText()));
        f.setValuefish(Integer.parseInt(texValuefish.getText()));
        f.setValuepenguin(Integer.parseInt(texValuepenguin.getText()));
        f.setImage(texFoodImage.getText());
        RaiseMeUp.updateFood(f);
        clearTextFields();
        listFoods();
    }//GEN-LAST:event_butUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFoods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butBack;
    private javax.swing.JButton butRemove;
    private javax.swing.JButton butUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableFoods;
    private javax.swing.JTextField texFoodImage;
    private javax.swing.JTextField texFoodName;
    private javax.swing.JTextField texFoodPrice;
    private javax.swing.JTextField texValuecat;
    private javax.swing.JTextField texValuedog;
    private javax.swing.JTextField texValuefish;
    private javax.swing.JTextField texValuepenguin;
    // End of variables declaration//GEN-END:variables
}
