/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raisemeup.view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import raisemeup.control.RaiseMeUp;
import raisemeup.model.beans.Pet;
import raisemeup.model.beans.Job;

/**
 *
 * @author lekogabor
 */
public class AdminJobs extends javax.swing.JFrame {

    
    private Map<Integer, Job> jobs = new HashMap<Integer, Job>();

    /**
     * Creates new form AdminJobs
     */
    public AdminJobs() {
        initComponents();
        myInit();
    }

    
    private void myInit(){
        listJobs();
        
        tableJobs.addMouseListener(new MouseAdapter(){
            
            public void mouseClicked(MouseEvent e){
                DefaultTableModel model = (DefaultTableModel) tableJobs.getModel();
                int i = tableJobs.getSelectedRow();

                
                texTitle.setText(model.getValueAt(i, 1).toString());
                texLenght.setText(model.getValueAt(i, 2).toString());
                texClient.setText(model.getValueAt(i, 3).toString());
                texMessage.setText(model.getValueAt(i, 4).toString());
                texImEnergy.setText(model.getValueAt(i, 5).toString());
                texImHunger.setText(model.getValueAt(i, 6).toString());
                texImHygiene.setText(model.getValueAt(i, 7).toString());
                texImFun.setText(model.getValueAt(i, 8).toString());
                texReward.setText(model.getValueAt(i, 9).toString());
                texSpecies.setText(model.getValueAt(i, 10).toString());
                texImage.setText(model.getValueAt(i, 11).toString());
            }
        });
    }
    
    private void listJobs(){
        jobs = RaiseMeUp.listJobs();        
        DefaultTableModel model = (DefaultTableModel) tableJobs.getModel();
        model.setRowCount(0);
        
        for (Map.Entry<Integer, Job> j : jobs.entrySet()){
            
            model.addRow(new Object[]{j.getValue().getId(), j.getValue().getTitle(), j.getValue().getLength(), j.getValue().getClient(), j.getValue().getMessage(),
                                    j.getValue().getImpactenergy(), j.getValue().getImpacthunger(), j.getValue().getImpacthygiene(),
                                    j.getValue().getImpactfun(), j.getValue().getReward(), j.getValue().getSpecies(), j.getValue().getImage()});
        }
    }
    
    private void clearTextFields(){
        texClient.setText("");
        texImEnergy.setText("");
        texImFun.setText("");
        texImHunger.setText("");
        texImHygiene.setText("");
        texImage.setText("");
        texLenght.setText("");
        texMessage.setText("");
        texTitle.setText("");
        texReward.setText("");
        texSpecies.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJobs = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        texTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        texLenght = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        texClient = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        texMessage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        texImEnergy = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        texImHunger = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        texImHygiene = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        texImFun = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        texImage = new javax.swing.JTextField();
        butUpdate = new javax.swing.JButton();
        butRemove = new javax.swing.JButton();
        butAdd = new javax.swing.JButton();
        butBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        texReward = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        texSpecies = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jLabel1.setText("Jobs");

        tableJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "jobID", "title", "length", "client", "message", "impactenergy", "impacthunger", "impacthygiene", "impactfun", "reward", "species", "image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableJobs);

        jLabel2.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel2.setText("Title");

        texTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texTitleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel3.setText("Length");

        texLenght.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texLenghtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel4.setText("Client");

        texClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texClientActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel5.setText("Message");

        texMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texMessageActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel6.setText("Impactenergy");

        texImEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texImEnergyActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel7.setText("Impacthunger");

        texImHunger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texImHungerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel8.setText("Impacthygiene");

        texImHygiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texImHygieneActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel9.setText("Impactfun");

        texImFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texImFunActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel10.setText("Image");

        texImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texImageActionPerformed(evt);
            }
        });

        butUpdate.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butUpdate.setText("Update");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        butRemove.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butRemove.setText("Remove");
        butRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRemoveActionPerformed(evt);
            }
        });

        butAdd.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butAdd.setText("Add");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });

        butBack.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        butBack.setText("Back");
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel11.setText("Reward");

        texReward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texRewardActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        jLabel12.setText("Species");

        texSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texSpeciesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texReward, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texLenght, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texClient, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texImEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texImHunger, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texImFun, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texImage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(58, 58, 58)
                                        .addComponent(texImHygiene, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(butAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(butRemove)
                                .addGap(49, 49, 49)
                                .addComponent(butUpdate)
                                .addGap(56, 56, 56)
                                .addComponent(butBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(texTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(texLenght, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(texMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(texImEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(texImHunger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(texImHygiene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(texImFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(texReward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(texSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(texImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAdd)
                    .addComponent(butRemove)
                    .addComponent(butUpdate)
                    .addComponent(butBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texTitleActionPerformed

    private void texLenghtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texLenghtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texLenghtActionPerformed

    private void texClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texClientActionPerformed

    private void texMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texMessageActionPerformed

    private void texImEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texImEnergyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texImEnergyActionPerformed

    private void texImHungerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texImHungerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texImHungerActionPerformed

    private void texImHygieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texImHygieneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texImHygieneActionPerformed

    private void texImFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texImFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texImFunActionPerformed

    private void texImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texImageActionPerformed

    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        Job j = new Job();
        
        j.setClient(texClient.getText());
        j.setImage(texImage.getText());
        j.setImpactenergy(Integer.parseInt(texImEnergy.getText()));
        j.setImpactfun(Integer.parseInt(texImFun.getText()));
        j.setImpacthunger(Integer.parseInt(texImHunger.getText()));
        j.setImpacthygiene(Integer.parseInt(texImHygiene.getText()));
        j.setTitle(texTitle.getText());
        j.setLength(Integer.parseInt(texLenght.getText()));
        j.setMessage(texMessage.getText());
        j.setReward(Integer.parseInt(texReward.getText()));
        j.setSpecies(texSpecies.getText());
        
        RaiseMeUp.newJob(j);
        clearTextFields();
        listJobs();
    }//GEN-LAST:event_butAddActionPerformed

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
        RaiseMeUp.setAdminWindow(new AdminWindow());
        this.setVisible(false);
        RaiseMeUp.getAdminWindow().setVisible(true);
    }//GEN-LAST:event_butBackActionPerformed

    private void texRewardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texRewardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texRewardActionPerformed

    private void texSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texSpeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texSpeciesActionPerformed

    private void butRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableJobs.getModel();
        int i = tableJobs.getSelectedRow();
        
        Job j = new Job();
        j.setId(Integer.parseInt(model.getValueAt(i, 0).toString()));
        RaiseMeUp.removeJob(j);
        clearTextFields();
        listJobs();
    }//GEN-LAST:event_butRemoveActionPerformed

    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableJobs.getModel();
        int i = tableJobs.getSelectedRow();
        
        Job j = new Job();
        
        j.setId(Integer.parseInt(model.getValueAt(i, 0).toString()));
        j.setClient(texClient.getText());
        j.setImage(texImage.getText());
        j.setImpactenergy(Integer.parseInt(texImEnergy.getText()));
        j.setImpactfun(Integer.parseInt(texImFun.getText()));
        j.setImpacthunger(Integer.parseInt(texImHunger.getText()));
        j.setImpacthygiene(Integer.parseInt(texImHygiene.getText()));
        j.setTitle(texTitle.getText());
        j.setLength(Integer.parseInt(texLenght.getText()));
        j.setMessage(texMessage.getText());
        j.setReward(Integer.parseInt(texReward.getText()));
        j.setSpecies(texSpecies.getText());
        
        RaiseMeUp.updateJob(j);
        clearTextFields();
        listJobs();
    }//GEN-LAST:event_butUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJobs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butBack;
    private javax.swing.JButton butRemove;
    private javax.swing.JButton butUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJobs;
    private javax.swing.JTextField texClient;
    private javax.swing.JTextField texImEnergy;
    private javax.swing.JTextField texImFun;
    private javax.swing.JTextField texImHunger;
    private javax.swing.JTextField texImHygiene;
    private javax.swing.JTextField texImage;
    private javax.swing.JTextField texLenght;
    private javax.swing.JTextField texMessage;
    private javax.swing.JTextField texReward;
    private javax.swing.JTextField texSpecies;
    private javax.swing.JTextField texTitle;
    // End of variables declaration//GEN-END:variables
}
