/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raisemeup.view;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import raisemeup.control.RaiseMeUp;
import raisemeup.model.beans.Food;

/**
 *
 * @author Andras
 */
public class FoodItem extends javax.swing.JPanel {

    Food food;
    int howmany;
    
    /**
     * Creates new form FoodItem
     */
    public FoodItem(Food food, int howmany) {
        this.food=food;
        this.howmany=howmany;
        initComponents();
        myInit();
    }
    
    private void myInit() {
        lblHowmany.setText("" + howmany);
        
        BufferedImage image=null;
        try {
            image = ImageIO.read(getClass().getResource("/images/" + food.getImage()));
        } catch (IOException ex) {
            Logger.getLogger(PetWindow.class.getName()).log(Level.SEVERE, "Cannot load Job!", ex);
            return;
        }
        image = RaiseMeUp.resizeImage(image, image.getType(), 82, 63);
        lblImg.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg = new javax.swing.JLabel();
        lblHowmany = new javax.swing.JLabel();
        butEat = new javax.swing.JButton();

        lblHowmany.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblHowmany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        butEat.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        butEat.setText("Eat");
        butEat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butEat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHowmany, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
            .addComponent(butEat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblHowmany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butEat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butEatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEatActionPerformed
        if(RaiseMeUp.getCurrentPet().getType().equals("dog")) RaiseMeUp.getCurrentPet().setHunger(RaiseMeUp.getCurrentPet().getHunger()+food.getValuedog());
        else if(RaiseMeUp.getCurrentPet().getType().equals("cat")) RaiseMeUp.getCurrentPet().setHunger(RaiseMeUp.getCurrentPet().getHunger()+food.getValuecat());
        else if(RaiseMeUp.getCurrentPet().getType().equals("fish")) RaiseMeUp.getCurrentPet().setHunger(RaiseMeUp.getCurrentPet().getHunger()+food.getValuefish());
        else RaiseMeUp.getCurrentPet().setHunger(RaiseMeUp.getCurrentPet().getHunger()+food.getValuepenguin());
        
        if(RaiseMeUp.getCurrentPet().getHunger()>100) RaiseMeUp.getCurrentPet().setHunger(100);
        
        int num = RaiseMeUp.getCurrentPet().getOwneditems().get(food);
        num--;
        if(num==0) {
            RaiseMeUp.getCurrentPet().getOwneditems().remove(food);
            RaiseMeUp.removeFoodOwned(RaiseMeUp.getCurrentPet(), food);
        }
        else {
            RaiseMeUp.getCurrentPet().getOwneditems().remove(food);
            RaiseMeUp.getCurrentPet().getOwneditems().put(food, num);
            RaiseMeUp.updateFoodOwned(RaiseMeUp.getCurrentPet(), food, num);
        }
        RaiseMeUp.getPetWindow().refreshPBHunger();
        RaiseMeUp.getPetWindow().refreshMenu();
    }//GEN-LAST:event_butEatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butEat;
    private javax.swing.JLabel lblHowmany;
    private javax.swing.JLabel lblImg;
    // End of variables declaration//GEN-END:variables
}
