/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raisemeup.view;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import raisemeup.control.RaiseMeUp;
import raisemeup.model.ItemVisitor;
import raisemeup.model.beans.Food;
import raisemeup.model.beans.Item;
import raisemeup.model.beans.Upgrade;

/**
 *
 * @author Kicsi Andras
 */
public class MarketWindow extends javax.swing.JFrame {

    private List<Item> cart = new ArrayList<>();
    
    /**
     * Creates new form MarketWindow
     */
    public MarketWindow() {
        initComponents();
        myInit();
    }
    
    private void myInit() {
        panMarket.setLayout(new GridLayout(0,3));
        
        Map<Integer, Food> food = new HashMap<>();
        food = RaiseMeUp.listFoods();
        
        Map<Integer, Upgrade> upgrades = new HashMap<>();
        upgrades = RaiseMeUp.listUpgrades();
        
        List<Item> items = new ArrayList<>();
        for(Map.Entry<Integer, Food> f : food.entrySet()) {
            items.add(f.getValue());
        }
        for(Map.Entry<Integer, Upgrade> u : upgrades.entrySet()) {
            if(u.getValue().getSpecies().equals(RaiseMeUp.getCurrentPet().getType())) {
                items.add(u.getValue());
            }
        }
        
        for(int i=0; i<items.size(); i++) {
            PanMarketElement element = new PanMarketElement(items.get(i));
            panMarket.add(element);
            element.setLocation(i*218, 0);
        }
        
        panMarket.repaint();
        panMarket.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panMarket = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panCart = new javax.swing.JPanel();
        butConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        butClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Market");

        butBack.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        butBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackButton.png"))); // NOI18N
        butBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMarketLayout = new javax.swing.GroupLayout(panMarket);
        panMarket.setLayout(panMarketLayout);
        panMarketLayout.setHorizontalGroup(
            panMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        panMarketLayout.setVerticalGroup(
            panMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panMarket);

        javax.swing.GroupLayout panCartLayout = new javax.swing.GroupLayout(panCart);
        panCart.setLayout(panCartLayout);
        panCartLayout.setHorizontalGroup(
            panCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        panCartLayout.setVerticalGroup(
            panCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panCart);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        butConfirm.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        butConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConfirmButton.png"))); // NOI18N
        butConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfirmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total price:");

        lblPrice.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrice.setText("0");

        butClear.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        butClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EmptyButton.png"))); // NOI18N
        butClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(butBack, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butClear, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_butBackActionPerformed

    public void addToCart(Item i) {
        cart.add(i);
        refreshCart();
    }
    
    public void refreshCart() {
        panCart.removeAll();
        
        ItemVisitor visitor = new ItemVisitor();
        
        int totalprice=0;
        
        int num=cart.size()-1;
        
        if(panCart.getPreferredSize().width<((cart.size()*40)+60)) panCart.setPreferredSize(new Dimension(((cart.size()*40)+60), panCart.getPreferredSize().height));
        
        for(Item i : cart) {
            
                if(i instanceof Food) totalprice+=visitor.visit((Food)i);
                else totalprice+=visitor.visit((Upgrade)i);
                
                
                BufferedImage image=null;

                try {
                    image = ImageIO.read(getClass().getResource("/images/" + i.getImage()));
                } catch (IOException ex) {
                    Logger.getLogger(PetWindow.class.getName()).log(Level.SEVERE, "Cannot load Job!", ex);
                    return;
                }
                image = RaiseMeUp.resizeImage(image, image.getType(), 100);

                JLabel lbl = new JLabel(new ImageIcon(image));
                panCart.add(lbl);
                lbl.setSize(100, 100);
                lbl.setLocation(num*40, 0);

                num--;
            }
        lblPrice.setText("" + totalprice);
        
        panCart.repaint();
        panCart.revalidate();
    }
    
    private void butConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConfirmActionPerformed
        int totalprice = Integer.parseInt(lblPrice.getText());
        
        if(RaiseMeUp.getCurrentPet().getMoney()<totalprice) {
            RaiseMeUp.setErrorMessage(new ErrorMessage("You don't have enough money to buy all this stuff!."));
            RaiseMeUp.getErrorMessage().setVisible(true);
            return;
        }
        
        RaiseMeUp.getCurrentPet().setMoney(RaiseMeUp.getCurrentPet().getMoney()-totalprice);
        
        for(Item i : cart) {
            boolean contained=false;
            Item m=null;
            int num=0;
            for(Entry<Item,Integer> masik : RaiseMeUp.getCurrentPet().getOwneditems().entrySet()) {
                if(masik.getKey().getName().equals(i.getName())) {
                    contained=true;
                    num = masik.getValue();
                    m=masik.getKey();
                }
            }
            if(contained) {
                num++;
                RaiseMeUp.getCurrentPet().getOwneditems().replace(m, num);
                if(i instanceof Food) {
                    RaiseMeUp.updateFoodOwned(RaiseMeUp.getCurrentPet(), (Food)i, num);
                }
            }
            else {
                RaiseMeUp.getCurrentPet().getOwneditems().put(i, 1);
                if(i instanceof Food) {
                    System.out.println("EZ KAJA");
                    RaiseMeUp.newFoodOwned(RaiseMeUp.getCurrentPet(), (Food)i, 1);
                }
                else {
                    RaiseMeUp.newUpgradeOwned(RaiseMeUp.getCurrentPet(), (Upgrade)i, 1);
                    RaiseMeUp.getPetWindow().refreshContent();
                    RaiseMeUp.getPetWindow().refreshUps();
                }
            }
        }
        
        RaiseMeUp.updatePet(RaiseMeUp.getCurrentPet());
        RaiseMeUp.getPetWindow().refreshMenu();
        RaiseMeUp.getPetWindow().refreshMoney();
        
        this.setVisible(false);
    }//GEN-LAST:event_butConfirmActionPerformed

    private void butClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearActionPerformed
        cart.clear();
        refreshCart();
    }//GEN-LAST:event_butClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBack;
    private javax.swing.JButton butClear;
    private javax.swing.JButton butConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JPanel panCart;
    private javax.swing.JPanel panMarket;
    // End of variables declaration//GEN-END:variables
}
