/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raisemeup.view;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import raisemeup.control.RaiseMeUp;
import raisemeup.model.beans.Food;
import raisemeup.model.beans.Item;
import raisemeup.model.beans.Upgrade;

/**
 *
 * @author Andras
 */
public class PanMarketElement extends javax.swing.JPanel {

    Item item;
    
    /**
     * Creates new form PanMarketElement
     */
    public PanMarketElement(Item item) {
        this.item = item;
        initComponents();
        myInit();
    }
    
    private void myInit() {
        lblItemName.setText(item.getName());
        
        if(RaiseMeUp.getCurrentPet().getOwneditems().containsKey(item)) {
            butBuy.setEnabled(false);
        }
        
        if(item instanceof Food) {
            this.setBackground(new Color(158, 242, 167));
            butBuy.setBackground(new Color(78, 183, 85));
        }
        else if(item instanceof Upgrade) {
            this.setBackground(new Color(183, 237, 217));
            butBuy.setBackground(new Color(69, 175, 157));
        }
        
        BufferedImage image=null;
        
        //Coin icon
        try {
            image = ImageIO.read(getClass().getResource("/images/Coin.png"));
        } catch (IOException ex) {
            Logger.getLogger(PetWindow.class.getName()).log(Level.SEVERE, "Cannot load Coin!", ex);
        }
        image = RaiseMeUp.resizeImage(image, image.getType(), 40);
        lblCoinIcon.setIcon(new ImageIcon(image));
        
        lblPrice.setText("" + item.getPrice());
        
        
        try {
            image = ImageIO.read(getClass().getResource("/images/" + item.getImage()));
        } catch (IOException ex) {
            Logger.getLogger(PetWindow.class.getName()).log(Level.SEVERE, "Cannot load Item image!", ex);
            return;
        }
        image = RaiseMeUp.resizeImage(image, image.getType(), 198);
        lblImage.setIcon(new ImageIcon(image));
        
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblItemName = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        butBuy = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();
        lblCoinIcon = new javax.swing.JLabel();

        lblItemName.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        lblItemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemName.setText("Name");

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        butBuy.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        butBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BuyButton.png"))); // NOI18N
        butBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuyActionPerformed(evt);
            }
        });

        lblPrice.setFont(new java.awt.Font("Hobo Std", 0, 22)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(butBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCoinIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lblCoinIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuyActionPerformed
        RaiseMeUp.getMarketWindow().addToCart(item);
    }//GEN-LAST:event_butBuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBuy;
    private javax.swing.JLabel lblCoinIcon;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblPrice;
    // End of variables declaration//GEN-END:variables
}
