/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raisemeup.view;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import raisemeup.control.RaiseMeUp;
import raisemeup.model.beans.Job;
import raisemeup.model.beans.Pet;

/**
 *
 * @author Andras
 */
public class PanPetElement extends javax.swing.JPanel {

    Pet pet;
    boolean hasjob=false;
    Job job=null;
    int progress;
    
    /**
     * Creates new form PanPetElement
     */
    public PanPetElement(Pet pet) {
        this.pet=pet;
        initComponents();
        myInit();
    }
    
    void myInit() {
        BufferedImage image=null;
        try {
            image = ImageIO.read(getClass().getResource("/images/" + pet.getImage()));
        } catch (IOException ex) {
            Logger.getLogger(PetWindow.class.getName()).log(Level.SEVERE, "Cannot load Pet!", ex);
        }
        image = RaiseMeUp.resizeImage(image, image.getType(), 140);
        lblPetDisplay.setIcon(new ImageIcon(image));
        lblPetName.setText(pet.getName());
        if(pet.getEmotion()==2) lblPetDisplay.setBackground(new Color(153,255,153));
        else if(pet.getEmotion()==1) lblPetDisplay.setBackground(new Color(255,255,153));
        else lblPetDisplay.setBackground(new Color(255,51,51));
        lblPetDisplay.setOpaque(true);
        
        
        for(Map.Entry<Job,Integer> j : pet.getOwnedjobs().entrySet()) {
            hasjob=true;
            job=j.getKey();
            progress=j.getValue();
        }
        
        if(hasjob) lblPetDisplay.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPetDisplay = new javax.swing.JLabel();
        lblPetName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 51)));
        setPreferredSize(new java.awt.Dimension(176, 276));

        lblPetDisplay.setBackground(new java.awt.Color(255, 51, 51));
        lblPetDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPetDisplay.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 51)));

        lblPetName.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        lblPetName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPetName.setText("PetName");
        lblPetName.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 51)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SelectButton.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeleteButton.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPetName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPetDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPetDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(hasjob) {
            RaiseMeUp.setCurrentJob(job);
            RaiseMeUp.setJobprogress(progress);
            RaiseMeUp.setOnJob(true);
        }
        
        RaiseMeUp.setPetWindow(new PetWindow(pet));
        RaiseMeUp.getPetChooser().setVisible(false);
        RaiseMeUp.getPetWindow().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RaiseMeUp.deletePet(pet);
        this.setVisible(false);
        RaiseMeUp.getPetChooser().repaint();
        RaiseMeUp.getPetChooser().revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblPetDisplay;
    private javax.swing.JLabel lblPetName;
    // End of variables declaration//GEN-END:variables
}
