/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raisemeup.view;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import raisemeup.control.RaiseMeUp;
import raisemeup.model.beans.Upgrade;

/**
 *
 * @author Andras
 */
public class UpgradeItem extends javax.swing.JPanel {

    Upgrade upgrade;
    
    /**
     * Creates new form MenuItem
     */
    public UpgradeItem(Upgrade upgrade) {
        this.upgrade=upgrade;
        initComponents();
        myInit();
    }
    
    private void myInit() {
        BufferedImage image=null;
        try {
            image = ImageIO.read(getClass().getResource("/images/" + upgrade.getImage()));
        } catch (IOException ex) {
            Logger.getLogger(PetWindow.class.getName()).log(Level.SEVERE, "Cannot load Job!", ex);
            return;
        }
        image = RaiseMeUp.resizeImage(image, image.getType(), 82, 63);
        lblImg.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg = new javax.swing.JLabel();
        butDelete = new javax.swing.JButton();

        butDelete.setBackground(new java.awt.Color(224, 234, 255));
        butDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RedX.png"))); // NOI18N
        butDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butDelete.setMargin(new java.awt.Insets(2, 2, 2, 2));
        butDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(butDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleteActionPerformed
        RaiseMeUp.getCurrentPet().getOwneditems().remove(upgrade);
        RaiseMeUp.removeUpgradeOwned(RaiseMeUp.getCurrentPet(), upgrade);
        RaiseMeUp.getPetWindow().refreshMenu();
        RaiseMeUp.getPetWindow().refreshContent();
        RaiseMeUp.getPetWindow().refreshUps();
    }//GEN-LAST:event_butDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDelete;
    private javax.swing.JLabel lblImg;
    // End of variables declaration//GEN-END:variables
}
